version: '2.4'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus/
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    links:
      - alertmanager:alertmanager
      - node_exporter:node_exporter
    restart: on-failure

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - ./data/alertmanager/:/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.config.file=/etc/alertmanager/web.yml'
    links:
      - prometheus-webhook-dingtalk:prometheus-webhook-dingtalk
    restart: on-failure
  
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana/:/var/lib/grafana/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123123123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: on-failure

  prometheus-webhook-dingtalk:
    image: timonwong/prometheus-webhook-dingtalk:latest
    container_name: prometheus-webhook-dingtalk
    ports:
      - 127.0.0.1:8060:8060
    volumes:
      - ./prometheus-webhook-dingtalk:/etc/prometheus-webhook-dingtalk/
    command:
      - '--config.file=/etc/prometheus-webhook-dingtalk/config.yml'
      - '--web.enable-lifecycle'
    restart: on-failure

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    ports:
      - 127.0.0.1:9100:9100
    volumes:
      - '/:/host:ro'    
